chartio/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^features/', include('features.urls', namespace="features")),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'', include('django_browserid.urls'))
)

features/urls.py
from django.conf.urls import patterns, url, include
from features import views

# the name value is called by the url template tag
urlpatterns = patterns('',
    # ex: /features/
    url(r'^$', views.index, name='index'),
    # ex: /features/5/
    url(r'^(?P<feature_id>\d+)/$', views.detail, name='detail'),
    # ex: /features/new-feature/
    url(r'^new-feature$', views.create_feature, name='new-feature'),
    url(r'^edit/(?P<feature_id>\d+)/$', views.create_feature, name='new-feature'),
    url(r'^search/', include('haystack.urls')),
    # url(r'^search/$', views.search, name='search'),
)

features/models.py
from django.db import models
from django import forms
from django.forms import ModelForm, EmailField


class Customer(models.Model):
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.email


class Feature(models.Model):
    jira_id = models.IntegerField(null=True, unique=True)
    title = models.CharField(max_length=200)
    description = models.TextField()
    customers = models.ManyToManyField(Customer, related_name="features")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    feature = models.ForeignKey(Feature)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    commenter = models.CharField(max_length=50)


class FeatureForm(ModelForm):
    customer_email = EmailField(required=False)

    class Meta:
        model = Feature
        fields = ["jira_id", "title", "description"]


class AddCustomerForm(forms.Form):
    customer_email = EmailField()


class DeleteFeatureForm(ModelForm):
    class Meta:
        model = Feature
        fields = []


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["commenter", "text"]

features/views.py
from django.shortcuts import get_object_or_404, render, render_to_response
# from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from features.models import Feature, FeatureForm, Customer, AddCustomerForm, CommentForm
from django.db.models import Count
# from django.core.urlresolvers import reverse


# The render() function takes the request object as its first argument,
# a template name as its second argument and a dictionary as its optional third argument.

def index(request):
    latest_feature_list = Feature.objects.annotate(num_customers=Count('customers')).order_by('-num_customers')
    context = {'latest_feature_list': latest_feature_list}
    return render(request, 'features/index.html', context)


def detail(request, feature_id):
    feature = get_object_or_404(Feature, pk=feature_id)
    if request.method == 'POST':  # If the form has been submitted...
        if request.POST.get('comment'):
            commentform = CommentForm(request.POST)
            if commentform.is_valid():
                comment = commentform.save(commit=False)
                comment.feature = feature
                comment.save()
        elif request.POST.get('customer'):
            customerform = AddCustomerForm(request.POST)  # A form bound to the POST data
            if customerform.is_valid():  # All validation rules pass
                customer, _ = Customer.objects.get_or_create(email=customerform.cleaned_data['customer_email'])
                feature.customers.add(customer)
                return render(request, 'features/detail.html', {'feature': feature})
    else:
        customerform = AddCustomerForm()  # An unbound form
        commentform = CommentForm()
    return render(request, 'features/detail.html', {'feature': feature})


def customers(request, feature_id):
    response = "These are the requesters for feature %s."
    return HttpResponse(response % feature_id)


def create_feature(request, feature_id=None):
    form_data = request.POST if request.method == 'POST' else None

    if feature_id is not None:
        f = get_object_or_404(Feature, pk=feature_id)
    else:
        f = None

    form = FeatureForm(form_data, instance=f)  # An unbound form

    if request.method == 'POST':  # If the form has been submitted...
        if form.is_valid():  # All validation rules pass
            if request.POST.get('delete'):
                f.delete()
                return HttpResponseRedirect("/features/")
            else:
                feature = form.save()
                customer_email = form.cleaned_data['customer_email']
                if customer_email:
                    customer, _ = Customer.objects.get_or_create(email=customer_email)
                    feature.customers.add(customer)
                return HttpResponseRedirect('/features/%i/' % feature.id)

    return render(request, 'features/new-feature.html', {'form': form})


def search(request):
    return render_to_response('search/search.html', {'query': 'query'})

# def search(request):
#     sqs = SearchQuerySet()
#     form = SearchForm(request.POST, searchqueryset=sqs, load_all=False)
#     if form.is_valid():
#         return form.search()

features/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}Chartio{% endblock %}
        </title>
        <link rel="stylesheet" type="text/css" href="/static/features/style.css">
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,600' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="//cdn.jsdelivr.net/pure/0.6.0/pure-min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    </head>

    <body>

        <div class="pure-g header-nav">
            <div class="pure-u-2-5 padded">
                <a href="/features/">
                    <img src="https://chartio.com/logo/logo-black-transparent.png">
                    <h1>Features</h1>
                </a>
            </div>
            <div class="pure-u-2-5 padded">
                <form method="get" action="/features/search/" class="pure-form search-bar">
                    <input type="search" name="q">
                    <input type="submit" class="pure-button button-primary" value="Search">
                </form>
            </div>
            <div class="pure-u-1-5 padded">
                <a class="pure-button new-feature button-primary" href="/features/new-feature">Add new feature</a>
            </div>
        </div>

        <div class="pure-g">
            <div class="pure-u-1-1 padded">
                {% block content %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

features/templates/features/detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="pure-g">

        <div class="pure-u-3-4 padded-right">

            <div class="feature-body">
                <h1>
                    {{ feature.title }}
                </h1>
                <a class="pure-button edit-button" href="/features/edit/{{feature.id}}">
                    <i class="fa fa-pencil"></i>
                </a>

                <p style="clear: both">
                    <em>{{ feature.created }}</em>
                <br>
                    <a href="https://chartio.atlassian.net/browse/MAIN-{{feature.jira_id}}">
                        View on JIRA
                    </a>
                <p>
                    {{ feature.description }}
                </p>
            </div>

            <div class="comments">
                <h2>Comments</h2>

                 <form action="" method="post" class="pure-form pure-form-stacked">
                {% csrf_token %}
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                    <input id="commenter" type="text" name="commenter" value="" required placeholder="Your name">
                    <textarea cols="40" rows="3" id="text" type="text" name="text" value="" required placeholder="Comment text"></textarea>
                    <input type="submit" value="Add" name="comment" class="pure-button">
                </form>

                <ul>
                {% for comment in feature.comment_set.all %}
                    <li>{{comment.commenter}}&emsp;<em>{{comment.created}}</em>
                    <br>{{ comment.text }}</li>
                {% empty %}
                    <em>No comments yet.</em>
                {% endfor %}
                </ul>
            </div>
        </div>

        <div class="pure-u-1-4">
            <h2>Requesters ({{ feature.customers.count }})</h2>
            <ul>
            {% for customer in feature.customers.all %}
                <li>{{ customer.email }}</li>
            {% empty %}
                <em>No customers have requested this feature yet.</em>
            {% endfor %}
            </ul>

            <form action="" method="post" class="pure-form">
            {% csrf_token %}
            {{ form.customer_email.errors }}
                <input id="customer" type="email" name="customer_email" value="" required placeholder="email">
                <input type="submit" value="Add" name="customer" class="pure-button">
            </form>
        </div>

    </div>





{% endblock %}

features/templates/features/index.html
{% extends 'base.html' %}


{% block content %}

    {% if latest_feature_list %}
        <table class="feature-list">
            <tr>
                <th class="feature-name">Name</th>
                <th class="vote-count">Votes</th>

            </tr>
        {% for feature in latest_feature_list %}
            <tr>
                <td class="feature-name"><a href="{% url 'features:detail' feature.id %}">{{ feature.title }}</a></td>
                <td class="vote-count">{{ feature.customers.count }}</td>

            </tr>
        {% endfor %}
        </table>
    {% else %}
        <p>No features yet.</p>
    {% endif %}
{% endblock %}

features/templates/features/new-feature.html
{% extends 'base.html' %}

{% block content %}

<form method="post" action="" class="pure-form pure-form-stacked edit-form">{% csrf_token %}
    {{ form }}
    <br>

    {% if form.instance.pk %}
    <input type="submit" value="Delete" name="delete" class="pure-button button-error">
    {% endif %}
    <input type='submit' value='Submit' class="pure-button submit-button" />
</form>


{% endblock %}

features/templates/search/search.html
{% extends 'base.html' %}

{% block content %}
    <h1>Search results for <span class="search-results">{{query}}</span></h1>

    <form method="get" action="." class="pure-form">
<!--         <table>
            {{ form.as_table }}
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Search">
                </td>
            </tr>
        </table> -->

        {% if query %}

            {% for result in page.object_list %}
                <p>
                    <a href="/features/{{result.object.pk}}">{{ result.object.title }}</a>
                    <br>
                    {{ result.object.description |truncatechars:100}}
                </p>
            {% empty %}
                <p>No results found.</p>
            {% endfor %}

            {% if page.has_previous or page.has_next %}
                <div>
                    {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
                    |
                    {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
                </div>
            {% endif %}
        {% else %}
            {# Show some example queries to run, maybe query syntax, something else? #}
        {% endif %}
    </form>
{% endblock %}